In [1]:
from pycaret.classification import *
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
from tqdm import tqdm
import gc
import random
import lightgbm as lgb
import re
from sklearn.metrics import *
from sklearn.model_selection import KFold
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
train = pd.read_csv(r'C:\Users\gmlkd\machine-learning-exercises\10.DAYCON대회_사용자불편예지\training set\train_case2.csv')
train_problem = pd.read_csv(r'C:\Users\gmlkd\machine-learning-exercises\10.DAYCON대회_사용자불편예지\preprocessed data\new_train_problem.csv', parse_dates=['time'])
test = pd.read_csv(r'C:\Users\gmlkd\machine-learning-exercises\10.DAYCON대회_사용자불편예지\training set\test_case2.csv')
submission = pd.read_csv("C:/Users/gmlkd/data/시스템 품질 변화로 인한 사용자 불편 예지 AI 경진대회_data/sample_submission.csv")

In [3]:
train = train.to_numpy()
problem = np.zeros(15000)
problem[train_problem.user_id.unique() - 10000] = 1

train_x = train
train_y = problem

In [4]:
# Train
#-------------------------------------------------------------------------------------
# validation auc score를 확인하기 위해 정의
def f_pr_auc(probas_pred, y_true):
    labels=y_true.get_label()
    p, r, _ = precision_recall_curve(labels, probas_pred)
    score=auc(r,p) 
    return "pr_auc", score, True
#-------------------------------------------------------------------------------------
models     = []
recalls    = []
precisions = []
auc_scores   = []
threshold = 0.5
# 파라미터 설정
params =      {
                'boosting_type' : 'gbdt',
                'objective'     : 'binary',
                'metric'        : 'auc',
                'seed': 1015
                }
#-------------------------------------------------------------------------------------
# 5 Kfold cross validation
k_fold = KFold(n_splits=5, shuffle=True, random_state=42)
for train_idx, val_idx in k_fold.split(train_x):
    # split train, validation set
    X = train_x[train_idx]
    y = train_y[train_idx]
    valid_x = train_x[val_idx]
    valid_y = train_y[val_idx]

    d_train= lgb.Dataset(X, y)
    d_val  = lgb.Dataset(valid_x, valid_y)
    
    #run traning
    model = lgb.train(
                        params,
                        train_set       = d_train,
                        num_boost_round = 1000,
                        valid_sets      = d_val,
                        feval           = f_pr_auc,
                        verbose_eval    = 20, 
                        early_stopping_rounds = 3
                       )
    
    # cal valid prediction
    valid_prob = model.predict(valid_x)
    valid_pred = np.where(valid_prob > threshold, 1, 0)
    
    # cal scores
    recall    = recall_score(    valid_y, valid_pred)
    precision = precision_score( valid_y, valid_pred)
    auc_score = roc_auc_score(   valid_y, valid_prob)

    # append scores
    models.append(model)
    recalls.append(recall)
    precisions.append(precision)
    auc_scores.append(auc_score)

    print('==========================================================')

[LightGBM] [Info] Number of positive: 3633, number of negative: 8367
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002209 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5879
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 58
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302750 -> initscore=-0.834237
[LightGBM] [Info] Start training from score -0.834237
Training until validation scores don't improve for 3 rounds
Early stopping, best iteration is:
[2]	valid_0's auc: 0.796928	valid_0's pr_auc: 0.803588
[LightGBM] [Info] Number of positive: 4828, number of negative: 7172
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002251 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6078
[LightGBM] [Info] Number of data points in the train set: 12000, number of used feature

In [5]:
print(np.mean(auc_scores))

0.7993551366349869


In [6]:
train_x = pd.DataFrame(train_x)
train_y = pd.DataFrame(train_y)
train_y.columns = ['problem']
train = pd.concat([train_x,train_y], axis =1)
train

0         1         2         3         4         5         6  \
0     -0.268744 -0.340504 -0.239957 -0.414143  0.102027 -0.055185 -0.047764   
1      0.500848 -0.340504 -0.239957  4.011349 -0.064861 -0.055185 -0.047764   
2     -0.272916 -0.340504 -0.239957 -0.414143  0.096218 -0.055185 -0.047764   
3     -0.275951 -0.340504 -0.239957  0.146356 -0.064861 -0.055185 -0.047764   
4     -0.093888  0.651704 -0.239957 -0.414143 -0.064861 -0.055185 -0.047764   
...         ...       ...       ...       ...       ...       ...       ...   
14995 -0.316156 -0.340504 -0.239957 -0.053688 -0.064861 -0.055185 -0.047764   
14996 -0.387084 -0.340504 -0.239957 -0.414143 -0.062749 -0.055185 -0.047764   
14997 -0.078337  0.704060 -0.239957 -0.414143 -0.064861 -0.055185 -0.047764   
14998 -0.333983 -0.156620 -0.239957 -0.414143 -0.064861 -0.055185 -0.047764   
14999 -0.173920 -0.340504 -0.239957 -0.414143  0.234059 -0.055185 -0.047764   

              7         8         9        10        11        12       13  \
0     -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
1     -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
2     -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
3     -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
4     -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
...         ...       ...       ...       ...       ...       ...      ...   
14995 -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
14996 -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
14997 -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
14998 -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   
14999 -0.024537 -0.050453 -0.026486 -0.009173 -0.013527 -0.011326 -0.00921   

             14        15        16        17        18       19        20  \
0     -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   
1     -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   
2     -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   
3     -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   
4     -0.084309 -0.008165 -0.009902 -0.035379  0.164038 -0.01059 -0.019935   
...         ...       ...       ...       ...       ...      ...       ...   
14995 -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   
14996 -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   
14997 -0.084309 -0.008165 -0.009902 -0.035379  0.919317 -0.01059 -0.019935   
14998 -0.084309 -0.008165 -0.009902 -0.035379  0.177405 -0.01059 -0.019935   
14999 -0.084309 -0.008165 -0.009902 -0.035379 -0.277099 -0.01059 -0.019935   

             21        22        23        24        25        26        27  \
0     -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
1     -0.012796  1.267385 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
2     -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
3     -0.012796  0.079299 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
4     -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
...         ...       ...       ...       ...       ...       ...       ...   
14995 -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
14996 -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
14997 -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
14998 -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   
14999 -0.012796 -0.250725 -0.026621 -0.008165 -0.041437 -0.008165 -0.008165   

             28        29        30        31        32        33        34  \
0     -0.016768 -0.010397 -0.026337 -0.014996 -0.196852 -0.030118  0.085244   
1     -0.016768 -0.010397 -0.026337 -0.014996 -0.196852 -0.030118 -0.029046   
2    

In [8]:
clf = setup(data = train, target = "problem", silent=True, session_id=42, train_size=0.85) 

In [9]:
best_3 = compare_models(sort = 'AUC', n_select = 3)

In [10]:
blended = blend_models(estimator_list = best_3, fold = 5, method = 'soft')

In [11]:
pred_holdout = predict_model(blended)

In [12]:
final_model = finalize_model(blended)

In [15]:
# pycaret의 predict_model을 사용하기 위해 test의 모든 컬럼을 정수로 변경
t_columns = list(np.arange(0,74))
test.columns = t_columns

In [16]:
prep_pipe = get_config('prep_pipe')
transformed_unseen_data = prep_pipe.transform(test)

In [63]:
prections = final_model.predict_proba(transformed_unseen_data)[:,1]
prections

array([0.91528047, 0.37724455, 0.45742957, ..., 0.66312932, 0.87929147,
       0.51487411])

In [67]:
a = prections[:43262-30000]
b = prections[43262-30000:]

In [66]:
new = prections.mean()
new

0.4944148152602951

In [68]:
a = np.append(a, new)
print(a)
print(b)

[0.91528047 0.37724455 0.45742957 ... 0.44824058 0.35992413 0.49441482]
[0.34965652 0.3971697  0.35079405 ... 0.66312932 0.87929147 0.51487411]


In [70]:
prections = np.concatenate((a, b))
prections

array([0.91528047, 0.37724455, 0.45742957, ..., 0.66312932, 0.87929147,
       0.51487411])

In [72]:
submission['problem'] = prections
submission

user_id   problem
0        30000  0.915280
1        30001  0.377245
2        30002  0.457430
3        30003  0.841255
4        30004  0.823994
...        ...       ...
14994    44994  0.432040
14995    44995  0.495195
14996    44996  0.663129
14997    44997  0.879291
14998    44998  0.514874

[14999 rows x 2 columns]

In [73]:
submission.iloc[43262-30000]

user_id    43262.000000
problem        0.494415
Name: 13262, dtype: float64

In [75]:
submission.to_csv(r'C:\Users\gmlkd\machine-learning-exercises\10.DAYCON대회_사용자불편예지\submissions\submission_use_pipeline.csv', index=False)